/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package br.com.ceub.ltpii.provas.covid;

public class MessageUtilsTest {
    //    @Test public void testGetMessage() {
    //        assertEquals("Hello      World!", MessageUtils.getMessage());
    //    }
}
