/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("br.com.ceub.ltpii.provas.java-application-conventions")
}

dependencies {
    implementation("org.apache.commons:commons-text")
}

application {
    // Define the main class for the application.
    mainClass.set("br.com.ceub.ltpii.provas.app.App")
}
