/*
 * This file was generated by the Gradle "init" task.
 */

plugins {
    id("br.com.ceub.ltpii.provas.java-application-conventions")
    id("org.openjfx.javafxplugin") version "0.0.10"
}

dependencies {
    implementation("org.apache.commons:commons-text")
    implementation("com.google.code.gson:gson:2.8.7")

    implementation("org.openjfx:javafx-base:15:mac")
    implementation("org.openjfx:javafx-controls:15:mac")
    implementation("org.openjfx:javafx-fxml:15:mac")
    implementation("org.openjfx:javafx-graphics:15:mac")
}

application {
    // Define the main class for the application.
    mainClass.set("br.com.ceub.ltpii.provas.xadrez.gui.Tela")
}

javafx {
    version = "15.0.1"
    modules("javafx.controls", "javafx.fxml")
}
